####
#    Alfa Laval
#    Task 6012 : Create a Powershell script to process org pages
#    User Story 5994 : Create a Powershell script to iterate through csv file and create Pages, set page properties and create folder in document library
#    - part of code is re-used from script that creates Modern pages (author : Mihails Sotnicoks)
####
#
#   Script deletes all pages and folders that are created by script "Create_OrgPages.ps1" and is based on that script output
#
####


# ------------ input variables ------------
# URL for site and credentials for connection
$url = "https://contoso.sharepoint.com/sites/organization-page-site/"
$user = "admin@contoso.onmicrosoft.com"
$pssw = 'password' | ConvertTo-SecureString -asPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential ($user,$pssw)
Connect-PnPOnline -Url $url –Credentials $cred

# Provide path to output file that was generated by "Create_OrgPages.ps1" script
$csvFilePath = "C:\output_PageTemplatesWithUrl.csv"


# ------------ process data ------------
Write-host "Site: " $url

# read data from CSV
$csv = Get-Content $csvFilePath
Write-host "CSV contains [" ($csv.Length-1) "] entries "

for ($i = 0; $i -lt $csv.Count; $i++)
{ 
    $valuesRaw = $csv[$i].Split(';')
    $pageName = $valuesRaw[6].Trim()
    $folderUrl = $valuesRaw[7].Trim()

    Write-host " Page [$pageId] and folder [$folderUrl]" 
    try
    {
        $page = Get-PnPClientSidePage -Identity $pageName -ErrorAction SilentlyContinue	
        if ($page -ne $null) 
        {
            Remove-PnPClientSidePage -Identity $pageName -Force
            Write-host "   OK (page-deleted)"
        }
        else { Write-host " ---page-not-found" }

        $folder = Get-PnPFolder -Url $folderUrl -ErrorAction SilentlyContinue
        if ($folder -ne $null) 
        {
            Remove-PnPFolder -Name $folder.Name -Folder "Shared Documents" -Force
            Write-host "   OK (folder-deleted)"
        }
        else { Write-host " ---folder-not-found" }
    }
    catch [System.Exception]
    {
        Write-Host "--- ERROR-1 : Exception : " $_.Exception -f Red
    }
}
   
Disconnect-PnPOnline

Write-Host "End" -f Green -b DarkGreen
Write-host " "
Write-host " "